<h2>1993, David Ryan, <i>IMAGE CONTRA IMAGE</i>, Castlefield Gallery, catalogue essay</h2>
<blockquote>
<p>
It cannot be underestimated how important the confrontation with dominant aesthetic ideas can be for an artist during their formative years, and how these take root and inform their output long after superficial 'resemblances' have vanished. In Sharon Hall's case, as with many (one is tempted to say most) artists of her generation, it was a response to what was then called 'New Image' painting, as exemplified by European painters of then late 70's and early 80's. Unlike many of her contemporaries, she did not awake one morning to find herself transformed into a fully fledged expressionist painter of archetypal imagery. Hall's engagement with the problems raised during that period was much slower, thoughtful and intelligent. Now that we have the opportunity to see her recent paintings it is clear that many of the issues from this period still persist and have been doggedly refined into a critical consideration of how images can be used in painting, indeed, how they can be used in conjunction with their own opposition.
</p>
<p>

The imagery Hall has been concerned with over the last few years has encompassed a wide range of both chronology and subject matter (there is, however, a visual consistency which partly results from her choice of pre-photographic modes of reproduction as source material.) A mere listing might suffice here: texts and images from the letters and diaries of the '49ers', childrens primers and educational aids, 'the world turned upside down' tradition of populist prints, various early colonialist maps and engravings, as well as astronomical and navigational charts. The list might make clear her interest in the images: they are all self consciously 'historical', they create a sort of temporal distance between their original connotation and their current re-fabrication, they often reveal rhetorical purely ideological element, and, formally, their linearity enables a curious relationship to occur with the other oppositional elements in the painting, namely the seemingly autonomous systematic mark making that seems to unfold the 'time' of picture making in conjunction with the 'recitation' of the images. 
</p>
</blockquote>
