<h5>Castelfield Gallery 1993</h5>
<p>...in the recent paintings it becomes obvious that Hall has shifted her method. Instead of imposing a whole outlined oneness of intention upon the canvas she builds up a further layering of possible evidence through her working method. Instead of dealing absolutely by answering a question that could never be posed through painting she approaches the country's imperial past through a fragmented accumulation of drawing. An alternately faltering and fast line hints at recognisable images. These can be attractive, decisive and unclear all at the same time. This faltering and questioning thought process has by necessity lead to the rejection of a display of false clarity of vision. In the same way that Gerhard Richter paints the blur in order to show how both the personal and photographic memory are ungraspable and unreliable, Hall dissects and crosses the surface with a build up of delicate delineation.</p>
<p>The relation between the process of thought and the activity of drawing is particularly naked here. By laying a trail across the canvas she describes a conceptual journey. The solid ground of so many 'clear' historical narratives has been replaced by an active involvment. The soil has been loosened and disrupted. New territories are explored.</p>
<p><i>Sacha Craddock catalogue essay</i></p>
<p>In the star map paintings, the night sky becomes an arena for the projection of images which have now largely lost their meaning, and where we see representations of the major constellations together with elemental divinities and personages associated with fate (many of these relate to early navigational systems and the ‘age of discovery’); their presentation is often extremely fragmented and optically dissolved by the close toned harmonies. In a similar manner territorial maps are used for the painting ’Traces’ ,an almost total subversion of the original is achieved by re- using the image several times, and, by pushing the representation to its limit, it seemingly passes over into complete abstraction. These might be seen as the key to the new paintings, in the sense that we are deflected from any literal reading of the images because they are shattered through the very endeavour of the paintings, which force us to attend to so many other things. What is being presented is not the image as a carrier of meaning, but the possibility of representing an act of prohibition.</p>
<p><i>David Ryan, catalogue essay</i></p>
<p>Sharon Hall’s recent canvases are so odd and awkward I suspect they are much better than they at first appear. Although generally too airy to at all appeal to me, they nevertheless give me the kind of uncomfortable feelings that come from the viewing of truly adventurous work. In any case I’ve not seen a show quite like this anywhere before, and that’s got to be a good thing…..The work’s unrelieved surreal dizziness should be disturbing but its not; its more light headed like a mind tingle of intoxication...</p>
<p><i>Robert Clark, review of Castelfield exhibition, the Guardian</i></p>
<p>Through the intensely delicate marks, lines and fragments of freehand initiated wood cut trails; she translates the images in related clean colours from all directions, across painstaking blinds of line. She makes you investigate the truths only hinted at in initial viewing. A gorgeous fact of these paintings is that they make you watch them further, as if you might find a plough in the stars…..The stains and stitches of colour physically tighten your eye and brow, and you are constantly aware of the time involved in both making and emergence...</p>
<p><i>Sue Platt, review of Castelfield exhibition, City Life 1994</i></p>
